;;;;;;;;;;;;;;;;;;;
;;;Constant Aliases for PPU
;;;;;;;;;;;;;;;;;;;

PPU_CTRL   = $2000
PPU_MASK   = $2001
PPU_STATUS = $2002
OAM_ADDR   = $2003
OAM_DATA   = $2004
PPU_SCROLL = $2005
PPU_ADDR   = $2006
PPU_DATA   = $2007

;;Controller

JOYPAD1 = $4016
JOYPAD2 = $4017

;;;;;;;;;;;;;;;;;;;
;;; BUTTONS

A_BUTTON = $80
B_BUTTON = $40
SELECT_BUTTON = $20
START_BUTTON = $10
UP_BUTTON = $08
DOWN_BUTTON = $04
LEFT_BUTTON = $02
RIGHT_BUTTON = $01  

;;;;;;;;;;;;;;;;;;;
;;;; PHYSICS
;;;;;;;;;;;;;;;;;;;
MAXSPEED = 90
JUMPSPEED = 150

ACCEL = 1
STOP = 4
GRAVITY = 10
AIRDECELL = 50


;;;;;;;;;;;;;;;;;;;
;;;; ANIMATION
;;;;;;;;;;;;;;;;;;;

;;Player States
IDLE = 0
WALK = 2


;;Sprite tile references
BLANK = 0




